
//Authentication
export const AUTHENTICATION_SUCCESS= 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

//GetUserInfo Api Call
export const FETCHING_USER_INFO = 'FETCHING_USER_INFO'
export const FETCHED_USER_INFO = 'FETCHED_USER_INFO'
export const FETCH_USER_INFO_ERROR = 'FETCH_USER_INFO_ERROR'

export const LOGOUT = 'LOGOUT'