export const FETCH_LANGUAGES_AND_REGIONS_START = 'FETCH_LANGUAGES_AND_REGIONS_START';
export const FETCH_LANGUAGES_AND_REGIONS_SUCCESS = 'FETCH_LANGUAGES_AND_REGIONS_SUCCESS';
export const FETCH_LANGUAGES_AND_REGIONS_FAILED = 'FETCH_LANGUAGES_AND_REGIONS_FAILED';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const UPDATE_THEME = 'UPDATE_THEME';