export const FETCH_MOST_POPULAR_VIDEOS_START = 'FETCH_MOST_POPULAR_VIDEOS_START'
export const FETCH_MOST_POPULAR_VIDEOS_SUCCESS = 'FETCH_MOST_POPULAR_VIDEOS_SUCCESS'
export const FETCH_MOST_POPULAR_VIDEOS_ERROR = 'FETCH_MOST_POPULAR_VIDEOS_ERROR'

export const FETCH_VIDEO_CATEGORIES_START = 'FETCH_VIDEO_CATEGORIES_START'
export const FETCH_VIDEO_CATEGORIES_SUCCESS = 'FETCH_VIDEO_CATEGORIES_SUCCESS'
export const FETCH_VIDEO_CATEGORIES_ERROR = 'FETCH_VIDEO_CATEGORIES_ERROR'