export const FETCH_LANGUAGES_AND_REGIONS_START = 'FETCH_LANGUAGES_AND_REGIONS_START';
export const FETCH_LANGUAGES_AND_REGIONS_SUCCESS = 'FETCH_LANGUAGES_AND_REGIONS_SUCCESS';
export const FETCH_LANGUAGES_AND_REGIONS_FAILED = 'FETCH_LANGUAGES_AND_REGIONS_FAILED';

export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';
export const UPDATE_THEME = 'UPDATE_THEME';
export const UPDATE_REGION = 'UPDATE_REGION';
